import type { CodegenConfig } from '@graphql-codegen/cli';

const codegenConfig: CodegenConfig = {
    overwrite: true,
    schema: 'apps/api/dist/autogenerated-schema.gql',
    documents: ['apps/web/**/*.graphql', 'packages/**/*.graphql'],
    generates: {
        'packages/data-access-graphql/src/lib/types.ts': {
            plugins: [
                'typescript',
                'typescript-operations',
                'typescript-graphql-request'
            ],
            config: {
                gqlImport: 'graphql-request#gql',
                pureMagicComment: true,
                optimizeDocumentNode: true,
                omitOperationSuffix: true
            }
        }
    }
};

export default codegenConfig;